#!/bin/sh
# Seed a default config on first install. Runs with OIS_CONFIG_DIR set.
# Idempotent: never clobber an existing config.
set -eu
cfg="$OIS_CONFIG_DIR/config.toml"
if [ ! -f "$cfg" ]; then
    mkdir -p "$OIS_CONFIG_DIR"
    cat > "$cfg" <<TOML
# Generated by exampled post-install hook
port = 9000
log_level = "info"
TOML
    # Tell OIS we created it, so uninstall cleans it up.
    printf 'file\t%s\tkeep\n' "$cfg" >> "$OIS_CLAIMS"
    echo "seeded default config at $cfg"
fi
